CREATE TABLE players(
	playerid INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(20) NOT NULL,
    points INTEGER NOT NULL,
    ans1 VARCHAR(1024) NOT NULL,
    ans2 VARCHAR(1024) NOT NULL
);

CREATE TABLE questions(
    questionid INTEGER PRIMARY KEY AUTOINCREMENT,
    question VARCHAR(1024) NOT NULL,
    name1 VARCHAR(20) NOT NULL,
    name2 VARCHAR(20) NOT NULL
);

CREATE TABLE votes(
    name VARCHAR(20) NOT NULL,
    questionid INTEGER NOT NULL,
    voteA INTEGER NOT NULL,
);